### ISSUE TITLE
metric names not following best practices

### ISSUE THREAD

**Issue by paulfantom** [mvazquezc/reverse-words#2]
Quickly looking at code I see there are two metrics: [`endpoints_accessed`](https://github.com/mvazquezc/reverse-words/blob/8e15500c2b9b88a7df388052078c831e3deb3865/main.go#L36) and [`total_reversed_words`](https://github.com/mvazquezc/reverse-words/blob/8e15500c2b9b88a7df388052078c831e3deb3865/main.go#L27). Judging by their descriptions and types they should be named as `endpoints_accessed_total` and `reversed_words_total`. Ideally, they could also be prefixed with the application name.

More about prometheus metric naming best practices can be read at https://prometheus.io/docs/practices/naming/#metric-names

**Comment by mvazquezc** [comment]
Hey @paulfantom ,

Thanks for the heads up. I just updated the code with the recommendations!
